#!/usr/bin/env bash
#
# build-combined.sh
# Regenerates cerberos-data-assurance-intelligence-layer-combined.md from the
# authoritative Confluence pages in confluence/.
#
# The combined file is a long-form reference copy only. The source of truth is
# always the individual pages under confluence/. Run this script after editing
# any confluence/*.md page to keep the combined file in sync.
#
# Usage:
#   ./build-combined.sh
#
set -euo pipefail

# Resolve the directory this script lives in, so it can be run from anywhere.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFLUENCE_DIR="${SCRIPT_DIR}/confluence"
OUTPUT_FILE="${SCRIPT_DIR}/cerberos-data-assurance-intelligence-layer-combined.md"

# Confluence pages in upload order (00 = parent, 01-14 = child pages).
PAGES=(
  "00-parent-page.md"
  "01-context-and-problem.md"
  "02-capability-and-architecture.md"
  "03-human-review-and-learning-loop.md"
  "04-governance-security-and-scale.md"
  "05-poc-roadmap-and-risks.md"
  "06-rule-types-data-model-and-examples.md"
  "07-logging-observability-and-monitoring.md"
  "08-jvm-agent-framework-options.md"
  "09-open-decisions-and-discovery-questions.md"
  "10-technology-selection-and-architecture-decision-report.md"
  "11-architecture-decision-summary.md"
  "12-executive-one-page-discovery-proposal.md"
  "13-supporting-technical-detail.md"
  "14-s3-parquet-glue-athena-analytical-assurance-layer.md"
)

# Table-of-contents titles (stable page names), in the same order as PAGES.
TOC_TITLES=(
  "Initial Discovery Concept"
  "Context and Problem"
  "Capability and Architecture"
  "Human Review and Learning Loop"
  "Governance, Security, and Scale"
  "PoC, Roadmap, and Risks"
  "Rule Types, Data Model, and Examples"
  "Logging, Observability, and Monitoring"
  "JVM Agent Framework Options"
  "Open Decisions and Discovery Questions"
  "Technology Selection and Architecture Decision Report"
  "Architecture Decision Summary"
  "Executive Discovery Proposal"
  "Supporting Technical Detail"
  "S3, Parquet, Glue Data Catalog and Athena Analytical Assurance Layer"
)

# Fail early if any expected page is missing.
for page in "${PAGES[@]}"; do
  if [[ ! -f "${CONFLUENCE_DIR}/${page}" ]]; then
    echo "ERROR: missing page ${CONFLUENCE_DIR}/${page}" >&2
    exit 1
  fi
done

# Write header and table of contents.
{
  echo "# Cerberos Data Assurance Intelligence Layer - Combined Discovery Pack"
  echo
  echo "> This file combines the Confluence parent page and all child pages into one long-form reference copy."
  echo "> The authoritative source should remain the individual Confluence pages in confluence/."
  echo "> Use this combined file only for private review, export, or continuity checks."
  echo "> Generated by build-combined.sh - do not edit by hand."
  echo
  echo "This combined file contains 15 sections in total: the parent page followed by 14 child pages."
  echo
  echo "## Table of Contents"
  echo
  for i in "${!TOC_TITLES[@]}"; do
    echo "$((i + 1)). ${TOC_TITLES[$i]}"
  done
} > "${OUTPUT_FILE}"

# Append each page, separated by a horizontal rule.
for page in "${PAGES[@]}"; do
  {
    echo
    echo "---"
  } >> "${OUTPUT_FILE}"
  cat "${CONFLUENCE_DIR}/${page}" >> "${OUTPUT_FILE}"
done

echo "Generated ${OUTPUT_FILE} from ${#PAGES[@]} pages."
